### ISSUE TITLE
Windows Change

### ISSUE THREAD

**Issue by frenshkosh** [savoisn/elixir-workshop#1]
Ajoutez:
https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe
Pas d'install via asdf:
Install Erland Msi (google)https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0~windows_amd64.exe
Install elixir Msi (google)https://repo.hex.pm/elixir-websetup.exe
Docker compose (inclus dans Docker)
Phoenix => `mix archive.install hex phx_new 1.4.0`
PostGres: 
```
docker pull postgres:11.1
docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 --name postgres_elixir postgres:11.1
```

Utiliser de préférence un git bash plus que le cmd windows

**Comment by savoisn** [comment]
thanks :)

Updated doc
