### ISSUE TITLE
How to resolve bcrypt_elixir compil problem

### ISSUE THREAD

**Issue by frenshkosh** [savoisn/elixir-workshop#2]
The main problem about this issue on Windows Platform is seemingly coming from a proper maker.
Which in the case is nmake coming along with Microsoft Visual Studio Build Tools (or Visual C++)

### Correction:
you can work with Chocolatey to get the adapted tools.

**Chocolatey**
check this link [https://chocolatey.org/docs/installation]
folllow steps for Installing Chocolatey chapter

**Visual C++ Build Tools**
> choco install VisualCppBuildTools

(and follow steps).
add C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin in your path

**Comment by savoisn** [comment]
Thanks man, I've been running linux only for sooo long I am kinda lost on windows ...

I'll edit the doc with your solution :+1:
Thanks again :D

**Comment by savoisn** [comment]
fixed in documentation thanks :)
https://github.com/savoisn/elixir-workshop/commit/d8a242cd812274ac3a19d15e38fbc1a9adbc59be
